### ISSUE TITLE
Content Editing in Locomotive

### ISSUE THREAD

**Issue by eeh53** [cul-it/mann-wagon#66]
### Suggested changes to content editor
> powered by [wysihtml](http://wysihtml.com)

- [x] ability to change font (size, style) **-- covered by #79**
- [x] ability to adjust spacing **-- covered by #79**
- [x] ability to edit photo without having to navigate to assets page **-- covered by #83**
- [x] ability to edit pdf link **-- covered by #84, #85**
- [x] ability to create forms/drops down lists  **-- forms on case-by-case basis, not via wysihtml**

  > See #74 as an example (rm 100/102 reservation form)

- [x] spellcheck feature  **-- covered by #86**
- [x] functioning number/bullet lists  **-- covered by #79**
- [x] pop-up window for hyperlink is very aggressive **-- covered by #85**
- [x] prompt/reminder to save changes when leaving a page  **-- covered by #87**
- [x] more features when editing tables (table fields, line weight, etc.) **-- covered by #79**
- [x] ability to add captions to images **-- covered by #79**

**Comment by cappadona** [comment]
Just met with @sew268 & @eeh53 to review al of these. Will be splitting them out to separate issues during the [Feb 2016 sprint](https://github.com/cul-it/mann-wagon/milestones/Feb%202016)

**Comment by cappadona** [comment]
Okay...I've created 6 issues that cover all of the suggestions and bug reports here.

**Comment by cappadona** [comment]
Closing this without team review since we all seemed to be in agreement on what had to be done when we met this morning.
